# Generated by Django 2.2.13 on 2021-01-13 11:24

from django.db import migrations


def collection_group_perms(apps, schema_editor):

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # get groups
    profile_admin = Group.objects.get(name="ProfileAdmin")

    # get collection permissions
    permissions = Permission.objects.filter(
        content_type__app_label="cms", content_type__model="content"
    ).values_list("id", flat=True)

    # Remove collection perms from ProfileAdmin group
    profile_admin.permissions.add(*permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(collection_group_perms),
    ]
