# Generated by Django 2.2.8 on 2020-01-21 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0006_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
