# Generated by Django 2.2.8 on 2020-01-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0007_auto_20200121_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
