# Generated by Django 2.2.8 on 2020-01-21 09:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0008_delete_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
