# Generated by Django 2.2.8 on 2020-01-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0011_auto_20200121_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='wardno',
            new_name='code',
        ),
    ]
