# Generated by Django 2.2.8 on 2020-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0015_country_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.FloatField(default=1220000),
            preserve_default=False,
        ),
    ]
