# Generated by Django 2.2.8 on 2020-01-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0025_auto_20200125_1452'),
        ('boundaries', '0016_country_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
    ]
