# Generated by Django 2.2.8 on 2020-01-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0025_auto_20200125_1452'),
        ('boundaries', '0017_province_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
        migrations.AddField(
            model_name='district',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
        migrations.AddField(
            model_name='mainplace',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
        migrations.AddField(
            model_name='subplace',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
        migrations.AddField(
            model_name='ward',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
    ]
