# Generated by Django 2.2.8 on 2020-02-14 07:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0037_auto_20200211_1929'),
        ('boundaries', '0020_ward_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geography', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography')),
            ],
        ),
        migrations.AddIndex(
            model_name='geographyboundary',
            index=models.Index(fields=['code'], name='boundaries__code_8ea6f4_idx'),
        ),
    ]
