# Generated by Django 2.2.8 on 2020-02-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0021_auto_20200214_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='mainplace',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='province',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='subplace',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='geography',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Mainplace',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Subplace',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
