# Generated by Django 2.2.10 on 2020-06-24 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0026_auto_20200329_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographyboundary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geographyboundary',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
