# Generated by Django 2.2.21 on 2021-08-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0116_auto_20210803_2049'),
        ('boundaries', '0027_auto_20200624_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographyboundary',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datasets.Version'),
        ),
        migrations.AlterField(
            model_name='geographyboundary',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.Geography'),
        ),
        migrations.AddConstraint(
            model_name='geographyboundary',
            constraint=models.UniqueConstraint(fields=('version', 'geography'), name='unique_geography_version'),
        ),
    ]
