# Generated by Django 2.2.24 on 2021-10-08 05:40

from django.db import migrations, models
import django.db.models.deletion


def set_boundary_version(apps, schema_editor):
    GeographyBoundary = apps.get_model("boundaries", "GeographyBoundary")
    Version = apps.get_model("datasets", "Version")
    cached_version_by_name = {v.name: v for v in Version.objects.all()}

    for boundary in GeographyBoundary.objects.all():
        boundary.version = cached_version_by_name[boundary.geography.version]
        boundary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0028_auto_20210803_2050'),
    ]
    run_before = [
        ('datasets', '0118_remove_geography_version'),
    ]

    operations = [
        migrations.RunPython(set_boundary_version),
        migrations.AlterField(
            model_name='geographyboundary',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.Version'),
        ),
    ]
