# Generated by Django 2.2.24 on 2021-10-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0028_auto_20210803_2050'),
        ('datasets', '0117_auto_20210804_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographyboundary',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.Version'),
        ),
    ]
