# Generated by Django 2.2.10 on 2020-03-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datasets.Profile'),
        ),
    ]
