# Generated by Django 2.2.10 on 2020-03-30 20:05

from django.db import migrations


def create_choropleth_methods(apps, schema_editor):
    choropleth_method = apps.get_model('profile', 'ChoroplethMethod')
    methods = [
        ("sibling", "Choropleths are calculated using the sum of values of sibling geographies as the denominator. This is useful when comparing one geography with its siblings."),
        ("subindicator", "Calculated using the sum of values of subindicators as the denominator. This is useful for presenting a per capita value.")
    ]

    for (name, description) in methods:
        choropleth_method.objects.create(name=name, description=description)


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20200330_2004'),
    ]

    operations = [
        migrations.RunPython(create_choropleth_methods)
    ]
