# Generated by Django 2.2.10 on 2020-03-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '00064_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
