# Generated by Django 2.2.10 on 2020-03-31 10:36

from django.db import migrations


def forwards(apps, schema_editor):
    """
    create initial data for Licence model
    """
    Licence = apps.get_model('profile', 'Licence')

    for name in ["creative commons", "other"]:
        Licence.objects.create(name=name)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_licence'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
