# Generated by Django 2.2.10 on 2020-04-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0060_auto_20200406_1016'),
        ('profile', '0007_auto_20200331_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileKeyMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subindicator', models.CharField(max_length=32)),
                ('denominator', models.CharField(choices=[('absolute_value', 'Absolute value'), ('subindicators', 'Sub-indicators'), ('sibling', 'Sibling')], max_length=32)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.IndicatorSubcategory')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Indicator')),
            ],
        ),
    ]
