# Generated by Django 2.2.10 on 2020-04-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0070_auto_20200411_0621'),
        ('profile', '0010_auto_20200407_1155'),
    ]


    state_operations = [
        migrations.CreateModel(
            name='ProfileHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the indicator in the database', max_length=60)),
                ('label', models.CharField(blank=True, help_text='Label for the indicator displayed on the front-end', max_length=60)),
                ('subindicator', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('indicator', models.ForeignKey(help_text='Indicator on which this highlight is based on.', on_delete=django.db.models.deletion.CASCADE, to='datasets.Indicator', verbose_name='variable')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Profile')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
