# Generated by Django 2.2.10 on 2020-04-11 18:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0073_auto_20200411_1832'),
        ('profile', '0011_profilehighlight'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='ProfileIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label for the indicator displayed on the front-end', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('subindicators', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('choropleth_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.ChoroplethMethod')),
                ('indicator', models.ForeignKey(help_text='Indicator on which this indicator is based on.', on_delete=django.db.models.deletion.CASCADE, to='datasets.Indicator', verbose_name='variable')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Profile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.IndicatorSubcategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
