# Generated by Django 2.2.10 on 2020-04-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_indicatorcategory'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='IndicatorSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.IndicatorCategory')),
            ],
            options={
                'verbose_name_plural': 'Indicator Subcategories',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.IndicatorSubcategory'),
        ),
        migrations.AlterField(
            model_name='profilekeymetrics',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.IndicatorSubcategory'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
