# Generated by Django 2.2.10 on 2020-04-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0083_auto_20200411_2133'),
        ('profile', '0014_auto_20200411_2108'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geography_hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.GeographyHierarchy')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='indicatorcategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profilehighlight',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='indicators',
            field=models.ManyToManyField(through='profile.ProfileIndicator', to='datasets.Indicator', verbose_name='variables'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
