# Generated by Django 2.2.10 on 2020-04-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_auto_20200412_0544'),
        ('points', '0014_auto_20200412_0533'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Licence',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
