# Generated by Django 2.2.10 on 2020-04-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_delete_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilekeymetrics',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
            preserve_default=False,
        ),
    ]
