# Generated by Django 2.2.10 on 2020-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_profilekeymetrics_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilekeymetrics',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
