# Generated by Django 2.2.10 on 2020-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_profilekeymetrics_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilekeymetrics',
            name='denominator',
            field=models.CharField(choices=[('absolute_value', 'Absolute value'), ('subindicators', 'Sub-indicators'), ('sibling', 'Sibling')], help_text='Method for calculating the denominator that will normalise this value.', max_length=32),
        ),
        migrations.AlterField(
            model_name='profilekeymetrics',
            name='label',
            field=models.CharField(help_text='Text used for display to users.', max_length=100),
        ),
    ]
