# Generated by Django 2.2.10 on 2020-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0020_auto_20200419_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehighlight',
            name='denominator',
            field=models.CharField(choices=[('absolute_value', 'Absolute value'), ('subindicators', 'Sub-indicators'), ('sibling', 'Sibling')], default='absolute_value', help_text='Method for calculating the denominator that will normalise this value.', max_length=32),
            preserve_default=False,
        ),
    ]
