# Generated by Django 2.2.10 on 2020-04-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0021_profilehighlight_denominator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Indicator Categories'},
        ),
        migrations.AddField(
            model_name='indicatorcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
