# Generated by Django 2.2.10 on 2020-04-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0021_profilehighlight_denominator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('non_editable', 'Public But Non Editable')], default='public', max_length=32),
            preserve_default=False,
        ),
    ]
