# Generated by Django 2.2.10 on 2020-04-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0022_auto_20200420_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorsubcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Indicator Subcategories'},
        ),
        migrations.AddField(
            model_name='indicatorsubcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
