# Generated by Django 2.2.10 on 2020-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0022_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('non_editable', 'Public But Non Editable')], default='public', max_length=32),
        ),
    ]
