# Generated by Django 2.2.10 on 2020-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0024_auto_20200420_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileindicator',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='profileindicator',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
