# Generated by Django 2.2.10 on 2020-04-20 12:48

from django.db import migrations

def prepopulate_profile_indicator_order(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ProfileIndicator = apps.get_model("profile", "ProfileIndicator")
    for idx, pi in enumerate(ProfileIndicator.objects.all()):
        pi.order = idx
        pi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0025_auto_20200420_1248'),
    ]

    operations = [
        migrations.RunPython(prepopulate_profile_indicator_order),
    ]
