# Generated by Django 2.2.10 on 2020-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0026_auto_20200420_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilekeymetrics',
            options={'ordering': ['order'], 'verbose_name_plural': 'Profile key metrics'},
        ),
        migrations.AddField(
            model_name='profilekeymetrics',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
