# Generated by Django 2.2.10 on 2020-04-20 12:55

from django.db import migrations


def prepopulate_profile_keymetric_order(apps, schema_editor):
    ProfileKeyMetrics = apps.get_model("profile", "ProfileKeyMetrics")
    for idx, km in enumerate(ProfileKeyMetrics.objects.all()):
        km.order = idx
        km.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0027_auto_20200420_1255'),
    ]

    operations = [
        migrations.RunPython(prepopulate_profile_keymetric_order),
    ]
