# Generated by Django 2.2.10 on 2020-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0028_auto_20200420_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilehighlight',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='profilehighlight',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
