# Generated by Django 2.2.10 on 2020-04-20 13:28

from django.db import migrations


def prepopulate_profile_highlight_order(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ProfileHighlight = apps.get_model("profile", "ProfileHighlight")
    for idx, ph in enumerate(ProfileHighlight.objects.all()):
        ph.order = idx
        ph.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0029_auto_20200420_1327'),
    ]

    operations = [
        migrations.RunPython(prepopulate_profile_highlight_order),
    ]
