# Generated by Django 2.2.10 on 2020-04-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0032_auto_20200417_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_type',
            new_name='permission_type',
        ),
    ]
