# Generated by Django 2.2.10 on 2020-05-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0033_auto_20200422_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requires_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
