# Generated by Django 2.2.10 on 2020-05-08 07:51

from django.db import migrations
from guardian.shortcuts import get_perms_for_model, assign_perm, remove_perm


def create_groups_for_profiles(apps, schema_editor):

    Profile = apps.get_model("profile", "Profile")
    Group = apps.get_model('auth', 'Group')

    for profile in Profile.objects.filter(permission_type="private"):
        group, created = Group.objects.get_or_create(name=profile.name.lower())

        if created:
            for perm in get_perms_for_model(Profile):
                assign_perm(perm, group, profile)


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0035_auto_20200507_0306'),
    ]

    operations = [
        # Disabled migrations due to error
        # Added a fix in : 0040_auto_20200603_0628
        # migrations.RunPython(create_groups_for_profiles),
    ]
