# Generated by Django 2.2.10 on 2020-05-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_auto_20200521_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='requires_authentication',
        ),
    ]
