# Generated by Django 2.2.10 on 2020-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_remove_profile_requires_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilehighlight',
            name='name',
        ),
    ]
