# Generated by Django 2.2.10 on 2020-06-03 06:28

from django.db import migrations


def create_groups_for_profiles(apps, schema_editor):

    Profile = apps.get_model("profile", "Profile")
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    obj_permission_model = apps.get_model("guardian", "GroupObjectPermission")
    ContentType = apps.get_model('contenttypes', 'ContentType') 

    profile_perms = Permission.objects.filter(
        content_type__app_label='profile',
        content_type__model='profile'
    )
    profile_content_type = ContentType.objects.get_for_model(Profile)

    for profile in Profile.objects.all():
        group = Group.objects.filter(name=profile.name.lower()).first()

        if not group:
            group = Group.objects.create(name=profile.name)
        else:
            group.name = profile.name
            group.save()

        for perm in profile_perms:

            obj_permission_model.objects.get_or_create(
                content_type=profile_content_type,
                object_pk=profile.id,
                permission=perm,
                group=group
            )

class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0039_remove_profilehighlight_name'),
    ]

    operations = [
        migrations.RunPython(create_groups_for_profiles),
    ]