# Generated by Django 2.2.10 on 2020-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0040_auto_20200603_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
