# Generated by Django 2.2.10 on 2020-07-25 11:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0042_indicatorcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
