# Generated by Django 2.2.10 on 2020-08-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0044_auto_20200805_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilehighlight',
            name='label',
            field=models.CharField(blank=True, help_text='Label for the indicator displayed on the front-end', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='label',
            field=models.CharField(blank=True, help_text='Label for the indicator displayed on the front-end', max_length=255),
        ),
        migrations.AlterField(
            model_name='profilekeymetrics',
            name='label',
            field=models.CharField(help_text='Text used for display to users.', max_length=255),
        ),
    ]
