# Generated by Django 2.2.10 on 2020-08-27 09:09

from django.db import migrations, models
import django.db.models.deletion


def create_chart_presentation_methods(apps, schema_editor):

    DefaultChartPresentation = apps.get_model("profile", "DefaultChartPresentation")
    DefaultChartPresentation.objects.create(
        label="Value",
        presentation_type="absolute"
    )
    DefaultChartPresentation.objects.create(
        label="Percentage",
        presentation_type="perc"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0045_auto_20200821_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultChartPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=30)),
                ('presentation_type', models.CharField(max_length=30, verbose_name="type")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profileindicator',
            name='default_chart_presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.DefaultChartPresentation'),
        ),
        migrations.RunPython(create_chart_presentation_methods),
    ]
