# Generated by Django 2.2.10 on 2020-08-22 08:12

from django.db import migrations


def add_decimal_places_to_profile_config(apps, schema_editor):

    Profile = apps.get_model("profile", "Profile")
    for profile in Profile.objects.all():
    	config = profile.configuration
    	config["decimal_places"] = 2
    	profile.configuration = config
    	profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0045_auto_20200821_0613'),
    ]

    operations = [
    	migrations.RunPython(add_decimal_places_to_profile_config),
    ]
