# Generated by Django 2.2.10 on 2020-09-10 09:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0046_auto_20200822_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileindicator',
            name='chart_configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
