# Generated by Django 2.2.21 on 2021-07-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0113_dataset_content_type'),
        ('profile', '0047_profileindicator_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('indicator', 'indicator'), ('html', 'html')], default='indicator', max_length=32)),
                ('indicator', models.ForeignKey(help_text='Indicator on which content is based on', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.Indicator', verbose_name='content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profileindicator',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Content'),
        ),
    ]
