# Generated by Django 2.2.13 on 2021-04-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0047_profileindicator_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileindicator',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
