# Generated by Django 2.2.21 on 2021-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0048_profileindicator_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
