# Generated by Django 2.2.24 on 2021-10-07 10:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0048_profileindicator_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorcategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='indicatorsubcategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='content_type',
            field=models.CharField(choices=[('indicator', 'Indicator'), ('html', 'HTML')], default='indicator', max_length=32),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
