# Generated by Django 2.2.21 on 2021-07-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0048_profileindicator_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileindicator',
            name='choropleth_method',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='profile.ChoroplethMethod'),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='content_type',
            field=models.CharField(choices=[('indicator', 'Indicator'), ('html', 'HTML')], default='indicator', max_length=32),
        ),
    ]
