# Generated by Django 2.2.24 on 2021-11-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0050_historicalindicatorcategory_historicalindicatorsubcategory_historicallogo_historicalprofile_historic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicatorcategory',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicatorsubcategory',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicallogo',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofilehighlight',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofileindicator',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofilekeymetrics',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
