# Generated by Django 2.2.24 on 2022-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0051_auto_20211111_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicatorcategory',
            name='icon',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
