# Generated by Django 2.2.28 on 2022-07-11 07:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0051_auto_20211111_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofileindicator',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart')], default='bar', max_length=32),
        ),
        migrations.AddField(
            model_name='profileindicator',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart')], default='bar', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalprofileindicator',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Use this to help your users interpret the indicator effectively'),
        ),
        migrations.AlterField(
            model_name='historicalprofileindicator',
            name='indicator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datasets.Indicator', verbose_name='variable'),
        ),
        migrations.AlterField(
            model_name='historicalprofileindicator',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The profile to which this profile indicator belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Use this to help your users interpret the indicator effectively'),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Indicator', verbose_name='variable'),
        ),
        migrations.AlterField(
            model_name='profileindicator',
            name='profile',
            field=models.ForeignKey(help_text='The profile to which this profile indicator belongs', on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
