# Generated by Django 2.2.28 on 2022-07-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0052_auto_20220711_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofileindicator',
            name='choropleth_range',
            field=models.CharField(choices=[('by_subindicator', 'By Subindicator'), ('by_indicator', 'By Indicator')], default='by_subindicator', max_length=32),
        ),
        migrations.AddField(
            model_name='profileindicator',
            name='choropleth_range',
            field=models.CharField(choices=[('by_subindicator', 'By Subindicator'), ('by_indicator', 'By Indicator')], default='by_subindicator', max_length=32),
        ),
    ]
