# Generated by Django 2.2.28 on 2022-09-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0054_auto_20220726_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofilehighlight',
            name='indicator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The variable on which this highlight is based on.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datasets.Indicator', verbose_name='variable'),
        ),
        migrations.AlterField(
            model_name='historicalprofilehighlight',
            name='label',
            field=models.CharField(blank=True, help_text='Label for the profile highlight displayed on the front-end', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprofilehighlight',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The profile to which this profile highlight belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='historicalprofilekeymetrics',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The profile to which this key metric belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profilehighlight',
            name='indicator',
            field=models.ForeignKey(help_text='The variable on which this highlight is based on.', on_delete=django.db.models.deletion.CASCADE, to='datasets.Indicator', verbose_name='variable'),
        ),
        migrations.AlterField(
            model_name='profilehighlight',
            name='label',
            field=models.CharField(blank=True, help_text='Label for the profile highlight displayed on the front-end', max_length=255),
        ),
        migrations.AlterField(
            model_name='profilehighlight',
            name='profile',
            field=models.ForeignKey(help_text='The profile to which this profile highlight belongs', on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profilekeymetrics',
            name='profile',
            field=models.ForeignKey(help_text='The profile to which this key metric belongs', on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
