from .logo_admin import LogoAdmin
from .profile_indicator_admin import ProfileIndicatorAdmin
from .profile_key_metrics_admin import ProfileKeyMetricsAdmin
from .profile_highlight_admin import ProfileHighlightAdmin
from .indicator_category_admin import IndicatorCategoryAdmin