# Generated by Django 2.2.8 on 2020-02-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_coordinatefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
