# Generated by Django 2.2.8 on 2020-03-10 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0044_auto_20200310_2150'),
        ('points', '0005_theme_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatefile',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='points.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinatefile',
            name='document',
            field=models.FileField(help_text='File Type required : CSV | Fields that are required: Name, Longitude, latitude', upload_to='points/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.CreateModel(
            name='ProfileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label for the category to be displayed on the front-end', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
    ]
