# Generated by Django 2.2.10 on 2020-03-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20200310_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecategory',
            options={'verbose_name_plural': 'Profile Categories'},
        ),
    ]
