# Generated by Django 2.2.8 on 2020-03-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20200316_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Subtheme', 'verbose_name_plural': 'Subthemes'},
        ),
        migrations.AlterModelOptions(
            name='profilecategory',
            options={'verbose_name': 'Point Collection', 'verbose_name_plural': 'Point Collections'},
        ),
        migrations.AlterField(
            model_name='coordinatefile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.Category', verbose_name='subtheme'),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='points.Category', verbose_name='subtheme'),
        ),
        migrations.AlterField(
            model_name='profilecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.Category', verbose_name='subtheme'),
        ),
    ]
