# Generated by Django 2.2.8 on 2020-03-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
        ('points', '0008_auto_20200317_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatefile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.Task'),
        ),
    ]
