# Generated by Django 2.2.10 on 2020-03-28 12:53

import django.core.validators
from django.db import migrations, models
import wazimap_ng.points.models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_coordinatefile_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatefile',
            name='document',
            field=models.FileField(help_text='File Type required : CSV | Fields that are required: Name, Longitude, latitude', upload_to=wazimap_ng.points.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
