# Generated by Django 2.2.10 on 2020-03-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_auto_20200328_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('license', models.CharField(choices=[('creative commons', 'Creative Commons'), ('other', 'Other')], default='none', max_length=32)),
                ('profile_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='points.ProfileCategory')),
            ],
        ),
    ]
