# Generated by Django 2.2.10 on 2020-03-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_licence'),
        ('points', '0010_auto_20200328_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatefile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coordinatefile',
            name='title',
        ),
        migrations.AddField(
            model_name='coordinatefile',
            name='profile_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.ProfileCategory'),
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_license', to='profile.Licence')),
                ('profile_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='points.ProfileCategory')),
            ],
        ),
    ]
