# Generated by Django 2.2.10 on 2020-03-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_auto_20200331_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='license',
            new_name='licence',
        ),
    ]
