# Generated by Django 2.2.10 on 2020-03-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatefile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coordinatefile',
            name='title',
        ),
        migrations.AddField(
            model_name='coordinatefile',
            name='profile_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.ProfileCategory'),
        ),
    ]
