# Generated by Django 2.2.10 on 2020-04-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_auto_20200331_1256'),
        ('profile', '0015_auto_20200411_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]

