# Generated by Django 2.2.10 on 2020-04-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_auto_20200411_2129'),
        ('datasets', '0085_auto_20200412_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_licence', to='datasets.Licence'),
        ),
    ]
