# Generated by Django 2.2.10 on 2020-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0014_auto_20200412_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecategory',
            name='collection_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('non_editable', 'Public But Non Editable')], default='public', max_length=32),
        ),
    ]
