# Generated by Django 2.2.10 on 2020-04-28 12:17

from django.db import migrations, models
import django.db.models.deletion

def copy_metadata_to_general_metadata(apps, schema_editor):
    """
    copy metadata from points.MetaData to general.MetaData
    """
    points_MD = apps.get_model('points', 'MetaData')
    general_MD = apps.get_model('general', 'MetaData')

    for metadata in points_MD.objects.all():

        category = metadata.profile_category.category
        new_metadata = general_MD.objects.create(
            source=metadata.source,
            description=metadata.description,
            licence=metadata.licence
        )

        category.metadata = new_metadata
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_category_metadata'),
    ]

    operations = [
        migrations.RunPython(copy_metadata_to_general_metadata),
    ]
