# Generated by Django 2.2.10 on 2020-04-28 12:17

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('points', '0016_auto_20200422_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.MetaData'),
        ),
    ]
