# Generated by Django 2.2.10 on 2020-04-25 16:01

from django.db import migrations, models
import django.db.models.deletion



def set_profile_to_themes(apps, schema_editor):
    """
    copy profile from profile category to theme profile
    """
    ProfileCategory = apps.get_model('points', 'ProfileCategory')

    for category in ProfileCategory.objects.all():
        profile = category.profile
        theme = category.category.theme
        theme.profile = profile
        theme.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0033_auto_20200422_0901'),
        ('points', '0016_auto_20200422_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
            preserve_default=False,
        ),
        migrations.RunPython(set_profile_to_themes),
        migrations.RemoveField(
            model_name='profilecategory',
            name='profile',
        ),
    ]
