# Generated by Django 2.2.10 on 2020-04-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_category_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaData',
        ),
    ]
