# Generated by Django 2.2.10 on 2020-04-26 07:40

from django.db import migrations, models
import django.db.models.deletion


def change_metadata_link(apps, schema_editor):
    """
    change metadata link from profile category to category
    """
    MetaData = apps.get_model('points', 'MetaData')

    for metadata in MetaData.objects.all():
        metadata.category = metadata.profile_category.category
        metadata.save()


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_auto_20200425_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='points.Category'),
            preserve_default=False,
        ),
        migrations.RunPython(change_metadata_link),
        migrations.RemoveField(
            model_name='metadata',
            name='profile_category',
        ),
    ]
