# Generated by Django 2.2.10 on 2020-04-26 07:45

from django.db import migrations, models
import django.db.models.deletion


def change_points_upload(apps, schema_editor):
    """
    change upload link from profile category to category
    """
    CoordinateFile = apps.get_model('points', 'CoordinateFile')

    for coordinate_file in CoordinateFile.objects.all():
        if coordinate_file.profile_category:
            coordinate_file.category = coordinate_file.profile_category.category
            coordinate_file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('points', '0018_metadata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatefile',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.Category'),
        ),
        migrations.RunPython(change_points_upload),
        migrations.RemoveField(
            model_name='coordinatefile',
            name='profile_category',
        ),
    ]
