# Generated by Django 2.2.10 on 2020-04-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0019_auto_20200428_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='permission_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('non_editable', 'Public But Non Editable')], default='public', max_length=32),
        ),
    ]
