# Generated by Django 2.2.10 on 2020-04-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0033_auto_20200422_0901'),
        ('points', '0020_category_permission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
