# Generated by Django 2.2.10 on 2020-04-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0021_theme_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='profilecategory',
            options={'verbose_name': 'Profile Collection', 'verbose_name_plural': 'Profile Collections'},
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='points.Category', verbose_name='collection'),
        ),
        migrations.AlterField(
            model_name='profilecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.Category', verbose_name='collection'),
        ),
    ]
