# Generated by Django 2.2.10 on 2020-05-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0022_auto_20200429_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['profile__name']},
        ),
    ]
