# Generated by Django 2.2.10 on 2020-05-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0024_auto_20200507_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='permission_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=32),
        ),
    ]
