# Generated by Django 2.2.10 on 2020-05-21 08:00

from django.db import migrations, models
import django.db.models.deletion


def copy_name_of_coordinate_file(apps, schema_editor):
    """
    copy name of collection to coordinate file object
    """
    CoordinateFile = apps.get_model('points', 'CoordinateFile')

    for file_obj in CoordinateFile.objects.all():
        if file_obj.category is not None:
            name = file_obj.category.name
            file_obj.name = name
            file_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0036_auto_20200508_0751'),
        ('points', '0025_auto_20200512_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatefile',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(copy_name_of_coordinate_file),
        migrations.RemoveField(
            model_name='coordinatefile',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
