# Generated by Django 2.2.10 on 2020-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0027_auto_20200521_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatefile',
            name='collection_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
