# Generated by Django 2.2.10 on 2020-07-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0030_auto_20200624_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatefile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.Task'),
        ),
    ]
