# Generated by Django 2.2.10 on 2020-07-30 11:20

from django.db import migrations, models
import wazimap_ng.points.models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0031_auto_20200717_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(help_text='Optional image for point', null=True, upload_to=wazimap_ng.points.models.get_file_path),
        ),
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.CharField(blank=True, help_text='Optional url for this point', max_length=150, null=True),
        ),
    ]
