# Generated by Django 2.2.10 on 2020-08-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0033_profilecategory_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecategory',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_categories', to='points.Theme'),
        ),
    ]
