# Generated by Django 2.2.13 on 2020-09-28 22:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import wazimap_ng.points.models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0035_remove_profilecategory_permission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for point', null=True, upload_to=wazimap_ng.points.models.get_file_path),
        ),
    ]
