# Generated by Django 2.2.13 on 2020-09-28 23:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0036_auto_20200928_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
