# Generated by Django 2.2.13 on 2020-12-02 12:49

from django.db import migrations

def update_point_data(apps, schema_editor):
    Location = apps.get_model('points', 'Location')
    for location in Location.objects.all():
        data = location.data
        if type(data) == dict:
            data2 = [{"key": key, "value": value} for (key, value) in data.items()]
            location.data = data2
            location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0037_auto_20200928_2309'),
    ]


    operations = [
        migrations.RunPython(update_point_data, lambda apps, schema_editor: migrations.RunPython.noop),
    ]
