# Generated by Django 2.2.13 on 2021-01-08 09:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0038_auto_20201202_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecategory',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18),
        ),
    ]
