# Generated by Django 2.2.13 on 2021-01-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0038_auto_20201117_1559'),
        ('points', '0039_profilecategory_color'),
    ]

    operations = [
    ]
