# Generated by Django 2.2.13 on 2021-04-21 04:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0041_profilecategory_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecategory',
            name='visible_tooltip_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
