# Generated by Django 2.2.13 on 2021-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0027_auto_20200624_0311'),
        ('points', '0041_profilecategory_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='boundaries',
            field=models.ManyToManyField(related_name='locations', to='boundaries.GeographyBoundary'),
        ),
    ]
