# Generated by Django 2.2.13 on 2021-05-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0042_auto_20210507_1117'),
        ('points', '0042_auto_20210421_0453'),
    ]

    operations = [
    ]
