# Generated by Django 2.2.13 on 2021-04-06 11:40

from django.db import migrations


def update_location_boundaries(apps, schema_editor):
    Location = apps.get_model('points', 'Location')
    GeographyBoundary = apps.get_model('boundaries', 'GeographyBoundary')
    for location in Location.objects.all():
    	geo_boundaries = GeographyBoundary.objects.filter(geom__contains=location.coordinates)
    	if geo_boundaries:
	        location.boundaries.add(*geo_boundaries)
	        location.save()

class Migration(migrations.Migration):

    dependencies = [
        ('points', '0042_location_boundaries'),
    ]

    operations = [
    	migrations.RunPython(update_location_boundaries)
    ]
