# Generated by Django 2.2.24 on 2021-09-09 07:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0043_merge_20210514_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecategory',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
