# Generated by Django 2.2.28 on 2022-08-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0047_auto_20211111_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofilecategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='profilecategory',
            name='color',
        ),
    ]
