# Generated by Django 2.2.28 on 2022-08-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0048_auto_20220805_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofilecategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='profilecategory',
            name='icon',
        ),
    ]
