# Generated by Django 2.2.28 on 2022-09-16 07:33

from django.db import migrations


def add_theme_colors(apps, schema_editor):
    Theme = apps.get_model('points', 'Theme')
    Profile = apps.get_model('profile', 'Profile')
    color_palette = [
        ("#3a70ff", "theme-1"), ("#993aff", "theme-2"), ("#ad356d", "theme-3"),
        ("#f04f4f", "theme-4"), ("#ff3a8c", "theme-5"), ("#ff893a", "theme-6"),
        ("#e7bc20", "theme-7"), ("#48c555", "theme-8"), ("#2ccaad", "theme-9"),
        ("#0a8286", "theme-10")
    ]

    for profile in Profile.objects.all():
        themes = Theme.objects.filter(profile=profile).order_by("order")[:10]

        for idx, theme in enumerate(themes):
            theme.color = color_palette[idx][0]
            theme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0050_auto_20220916_0720'),
    ]

    operations = [
        migrations.RunPython(add_theme_colors)
    ]
