# Generated by Django 2.2.28 on 2023-09-08 17:58

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0051_add_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
