# Generated by Django 2.2.28 on 2023-09-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0052_location_content_search'),
    ]

    operations = [
    ]
