# Generated by Django 2.2.28 on 2023-09-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0053_auto_20230908_1810'),
    ]

    operations = [
    ]
