# Generated by Django 2.2.28 on 2023-09-08 18:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0054_auto_20230908_1810'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='points_loca_content_903b52_gin'),
        ),
    ]
