# Generated by Django 2.2.28 on 2023-09-12 06:48

from django.db import migrations
from django.contrib.postgres.search import SearchVector


def compute_search_vector(apps, schema_editor):
    Location = apps.get_model('points', 'Location')
    Location.objects.update(content_search=SearchVector("name", "url", "data"))


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0055_auto_20230908_1813'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION update_trigger() RETURNS trigger AS $$
            begin
            new.content_search :=
                setweight(to_tsvector('pg_catalog.english', coalesce(new.name,'')), 'A') ||
                setweight(to_tsvector('pg_catalog.english', coalesce(new.url,'')), 'A') ||
                setweight(to_tsvector('pg_catalog.english', coalesce(new.data::text, '')), 'A');
            return new;
            end
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE
            ON points_location
            FOR EACH ROW EXECUTE PROCEDURE
            update_trigger();
            UPDATE points_location SET content_search = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON points_location;
            """,
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
