# Generated by Django 2.2.28 on 2023-09-12 06:48

from django.db import migrations
from django.contrib.postgres.search import SearchVector


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0055_auto_20230908_1813'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION update_trigger() RETURNS trigger AS $$
            begin
            new.content_search :=
                setweight(to_tsvector('simple', coalesce(new.name,'')), 'A') ||
                setweight(to_tsvector('simple', coalesce(new.url,'')), 'A') ||
                setweight(to_tsvector('simple', coalesce(new.data::text, '')), 'A');
            return new;
            end
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE
            ON points_location
            FOR EACH ROW EXECUTE PROCEDURE
            update_trigger();
            UPDATE points_location SET content_search = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON points_location;
            """,
        )
    ]
