# Generated by Django 2.2.28 on 2023-09-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0055_auto_20230908_1813'),
    ]

    migration = """
            CREATE TRIGGER content_search_update BEFORE INSERT OR UPDATE
            ON location FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                content_search, 'pg_catalog.english', name, category, coordinates, data, url
        );
            -- Force triggers to run and populate the content_search column.
            UPDATE location set ID = ID;
        """

    reverse_migration = """
        DROP TRIGGER content_search_update ON location;
    """

    operations = [migrations.RunSQL(migration, reverse_migration)]
