from .profile_key_metrics import ProfileKeyMetricsForm
from .profile_highlight_form import ProfileHighlightForm
from .profile_indicator_form import ProfileIndicatorAdminForm
from .profile_admin_form import ProfileAdminForm