# Generated by Django 2.2.13 on 2020-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('error', 'error'), ('in_progress', 'in_progress')], default='info', max_length=20),
        ),
    ]
