# Generated by Django 2.2.8 on 2020-01-10 16:07

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
